### ISSUE TITLE
Toevoegen 'how-to' over uitbreidbaarheid van IMX-Geo voor toepassingen

### ISSUE THREAD

**Issue by adbgnm** [Geonovum/IMX-Geo#18]
De inhoud van dit document 
https://github.com/Geonovum/IMX-Geo/blob/main/extension.md

opnemen als toelichting/bijlage in het document over IMX-Geo 
om gebruikers van IMX-Geo informatie te geven over hoe zij zelf IMX-Geo kunnen uitbreiden met gegevens uit andere (sector)registraties.

**Comment by lvdbrink** [comment]
Dit onderdeel is in het Nederlands geschreven. Voor nu voeg ik het toe zonder het in het Engels te vertalen. Dit kan desgewenst alsnog.
